spring:
  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에 유용
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        hibernate.default_batch_fetch_size: 1000

#    #전송 쿼리 확인 h2 사용시 설정
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true


    #테이블 생성 후에 data.sql실행
    defer-datasource-initialization: true

  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rk
    username: root
    password: 1234
#    url: jdbc:h2:mem:testdb
#    username: sa
#
#  h2:
#    console:
#      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 386257786961-e3udpn75tlqvi29ejnkc3sagve80aqjf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot




